replicas: 1

imagePullSecrets: []

image:
  repository: "harbor.atosurnstack.lab/library/nginx@sha256:43cd1aa2a26fbe7e6a4f9ba6cc289ea885731fbafe078b62983325a60c8c2c56"
  imagePullPolicy: "Always"

resources:
  requests:
    memory: "64M"
    cpu: "200m"
  limits:
    memory: "256M"
    cpu: "1"

service:
  type: NodePort
